victoire_core:
    widgets:
        image:
            class: "Victoire\\Widget\\ImageBundle\\Entity\\WidgetImage"
            name: image

jms_translation:
    configs:
        victoire_image_bundle:
            dirs: ["@VictoireImageBundle"]
            output_dir: "@VictoireImageBundle/Resources/translations"
